### ISSUE TITLE
Contrato_Transaccion

### ISSUE THREAD

**Issue by JoseMalcaR** [TSSW2024/Contrato_Transaccion#1]
- [x]  1.Crear la api que traiga o exponga los datos de la BD.

- [x] 2.Crear endpoints para operaciones CRUD sobre las transacciones.

- [x] 3.Escribir la lógica para manejar las solicitudes a los endpoints y realizar las operaciones en la base de datos.
- [x]  4.Conectarse a la BD de Postgres en GCP.

**Comment by Manuxxrsb2** [comment]
Finish the mission
[api.zip](https://github.com/user-attachments/files/16101766/api.zip)

Lo que falta por terminar es de la tarea de Nicolas ....
